/* ServisDrama — Satışçı Paneli v2 (salt-okunur teknik veriler + satış aksiyonları) */
const API_HEADERS=()=>({'Content-Type':'application/json','Authorization':'Bearer '+(localStorage.getItem('token')||sessionStorage.getItem('token')||'')});
let currentPage='dashboard';
document.addEventListener('DOMContentLoaded',initializeSalesPanel);

async function initializeSalesPanel(){
  const user=SD.sessionUser();
  if(!user){location.href='index.html';return;}
  if(String(user.role||'').toLowerCase()!=='sales'){location.href='index.html';return;}
  try{await SD.remoteReady();const rep=SD.sessionSalesRep();if(!rep||rep.status==='inactive'){alert('Aktif satışçı profili bulunamadı.');doLogout();return;}initializeUI(user);showPage('dashboard');}
  catch(e){console.error(e);alert('Satışçı paneli yüklenemedi: '+e.message);}
}
function initializeUI(user){
  const initials=String(user.name||user.username||'?').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
  ['navAvatarImg','navDdAvatar'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=initials;});
  ['navUserLabel','navDdName'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=user.name||user.username;});
  document.querySelectorAll('.nav-tab[data-page]').forEach(t=>t.onclick=()=>{showPage(t.dataset.page);closeMobileMenu();});
  const form=document.getElementById('actionForm');if(form)form.addEventListener('submit',submitAction);
  const modal=document.getElementById('companyDetailModal');if(modal)modal.onclick=e=>{if(e.target===modal)closeCompanyDetail();};
  document.addEventListener('keydown',e=>{if(e.key==='Escape')closeCompanyDetail();});
}
function myRep(){return SD.sessionSalesRep();}
function myCompanies(){const r=myRep();return r?SD.companies.filter(c=>{const ids=[c.salesRepId,c.salesRepUserId].filter(Boolean).map(String);return ids.includes(String(r.id||''))||ids.includes(String(r.userId||''))||ids.includes(String(r.legacyUserId||''));}):[];}
function companyIdOf(x){return String(x?.firmaId||x?.companyId||'');}
function visitCompanyId(key){return String(key).split(/[|_]/)[0];}
function visitDate(x){const ts=Number(x?.ts);if(ts>0)return new Date(ts);const s=String(x?.date||x?.dayKey||'');if(/^\d{2}\.\d{2}\.\d{4}$/.test(s)){const [d,m,y]=s.split('.');return new Date(+y,+m-1,+d);}if(/^\d{2}\.\d{2}$/.test(s)){const [d,m]=s.split('.');let z=new Date(new Date().getFullYear(),+m-1,+d);if(z>Date.now()+864e5)z.setFullYear(z.getFullYear()-1);return z;}const z=new Date(s);return isNaN(z)?null:z;}
function entries(rec){return rec?.by&&typeof rec.by==='object'?Object.values(rec.by):(rec?[rec]:[]);}
function allVisitsForCompany(id){const out=[];Object.entries(SD.visits||{}).forEach(([k,r])=>{if(visitCompanyId(k)!==String(id))return;entries(r).forEach(v=>out.push({...v,_type:'normal',_date:visitDate(v)}));});(SD.extras||[]).forEach(x=>{if(companyIdOf(x)===String(id))out.push({...x,_type:'extra',_date:visitDate(x)});});return out.filter(x=>x._date).sort((a,b)=>b._date-a._date);}
function lastVisit(c){return allVisitsForCompany(c.id)[0]||null;}
function techLabel(v){const code=String(v?.techCode||v?.technicianCode||v?.tc||'');const t=(SD.technicians||[]).find(x=>String(x.code)===code||String(x.id)===String(v?.techId||''));return t?(t.name+' — '+(t.code||code)):(code||'Bilinmiyor');}
function weekIndex(d=new Date()){return Math.max(1,Math.min(4,Math.ceil(d.getDate()/7)));}
function scheduled(c,d=new Date()){const w=Array.isArray(c.weeks)&&c.weeks.length?c.weeks:[1,2,3,4];return w.includes(weekIndex(d));}
function visitedThisWeek(c){const now=new Date(),start=new Date(now);start.setDate(now.getDate()-((now.getDay()+6)%7));start.setHours(0,0,0,0);return allVisitsForCompany(c.id).some(v=>v._date>=start);}
function daysSince(v){return v?Math.floor((Date.now()-v._date.getTime())/864e5):null;}
function delayStatus(c){const l=lastVisit(c),days=daysSince(l),isPlan=scheduled(c),done=visitedThisWeek(c);if(isPlan&&done)return 'visited';if(isPlan&&!done&&new Date().getDay()>=5)return 'delayed';if(isPlan&&!done)return 'scheduled';if(days===null)return 'critical';if(days>90)return 'critical';if(days>60)return 'risk';return 'ok';}
function samplesFor(c){return (SD.load('sd_samples',[])||[]).filter(s=>companyIdOf(s)===String(c.id));}
function sampleOpen(s){const st=String(s.status||s.durum||s.sonuc||'').toLowerCase();return !/(kapandı|kapandi|iptal|sonuç geldi|sonuc geldi|tamamlandı|tamamlandi)/.test(st);}
function health(c){let score=100,reasons=[];const st=delayStatus(c),l=lastVisit(c),d=daysSince(l);if(st==='delayed'){score-=20;reasons.push('Planlı ziyaret gecikmiş');}if(st==='critical'){score-=35;reasons.push('Uzun süredir ziyaret yok');}else if(st==='risk'){score-=20;reasons.push('Son ziyaret 60 günü geçmiş');}if(d===null){score-=25;reasons.push('Ziyaret kaydı yok');}const open=samplesFor(c).filter(sampleOpen);if(open.length){score-=Math.min(25,open.length*8);reasons.push(open.length+' açık numune');}const recent=allVisitsForCompany(c.id).slice(0,3).map(techLabel);if(new Set(recent).size>=3){score-=10;reasons.push('Son ziyaretlerde teknisyen sürekliliği düşük');}score=Math.max(0,score);return{score,reasons,label:score>=80?'Sağlıklı':score>=60?'Takip':score>=40?'Riskli':'Kritik'};}
function showPage(name){currentPage=name;document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));document.getElementById(name+'Content')?.classList.remove('hidden');document.querySelectorAll('.nav-tab[data-page]').forEach(t=>t.classList.toggle('active',t.dataset.page===name));({dashboard:renderDashboard,firmalar:renderCompanies,ziyaretler:renderVisitHistory,numuneler:renderSamples,aksiyonlar:renderActions,bildirimler:renderNotifications}[name]||(()=>{}))();}
function renderDashboard(){const cs=myCompanies();const ss=(SD.load('sd_samples',[])||[]).filter(s=>cs.some(c=>String(c.id)===companyIdOf(s)));const stats=[['Toplam Firma',cs.length],['Bu Hafta Planlı',cs.filter(scheduled).length],['Bu Hafta Ziyaret',cs.filter(visitedThisWeek).length],['Geciken',cs.filter(c=>delayStatus(c)==='delayed').length],['Kritik',cs.filter(c=>delayStatus(c)==='critical').length],['30+ Gün Ziyaretsiz',cs.filter(c=>(daysSince(lastVisit(c))||0)>30).length],['Açık Numune',ss.filter(sampleOpen).length],['Riskli/Kritik Firma',cs.filter(c=>health(c).score<60).length]];document.getElementById('dashboardStats').innerHTML=stats.map(([a,b])=>`<div class="stat-card"><div class="stat-content"><div class="stat-value">${b}</div><div class="stat-label">${a}</div></div></div>`).join('');}
function renderCompanies(){const el=document.getElementById('companiesList'),cs=myCompanies();if(!cs.length){el.innerHTML='<p>Size atanmış firma yok.</p>';return;}el.innerHTML=cs.map(c=>{const l=lastVisit(c),h=health(c);return `<div class="company-card" onclick="showCompanyDetail('${escapeHtml(c.id)}')"><div class="company-name">${escapeHtml(c.name)}</div><div class="company-region">${escapeHtml(c.bolge||'-')}</div><div class="company-meta"><span>Son ziyaret: ${l?formatDate(l._date):'Yok'}</span><span>${escapeHtml(l?techLabel(l):'Teknisyen yok')}</span><span class="meta-badge">${h.label} · ${h.score}</span><span>${samplesFor(c).filter(sampleOpen).length} açık numune</span></div></div>`;}).join('');}
function renderVisitHistory(){const ids=new Set(myCompanies().map(c=>String(c.id))),rows=[];myCompanies().forEach(c=>allVisitsForCompany(c.id).forEach(v=>rows.push({...v,_company:c})));rows.sort((a,b)=>b._date-a._date);document.getElementById('visitHistory').innerHTML=rows.length?`<div class="visit-timeline">${rows.map(v=>`<div class="visit-entry"><div class="visit-date">${formatDate(v._date)} ${escapeHtml(v.saat||v.time||'')}</div><div class="visit-type">${v._type==='extra'?'Program Dışı':'Normal'} · ${escapeHtml(v._company.name)}</div><div class="visit-tech">${escapeHtml(techLabel(v))}</div>${visitDetails(v)}</div>`).join('')}</div>`:'<p>Ziyaret geçmişi yok.</p>';}
function visitDetails(v){const skip=new Set(['by','ts','date','dayKey','saat','time','tc','techCode','technicianCode','techId','firmaId','companyId','_type','_date','id']);const parts=Object.entries(v).filter(([k,val])=>!skip.has(k)&&val!==''&&val!=null&&typeof val!=='object').slice(0,20).map(([k,val])=>`<div><b>${escapeHtml(k)}:</b> ${escapeHtml(String(val))}</div>`);return parts.length?`<div class="visit-notes">${parts.join('')}</div>`:'';}
function renderSamples(){const cs=new Map(myCompanies().map(c=>[String(c.id),c]));const rows=(SD.load('sd_samples',[])||[]).filter(s=>cs.has(companyIdOf(s)));document.getElementById('samplesList').innerHTML=rows.length?rows.map(s=>`<div class="sample-card"><h3>${escapeHtml(cs.get(companyIdOf(s))?.name||'Firma')}</h3>${Object.entries(s).filter(([k,v])=>v!==''&&v!=null&&typeof v!=='object').map(([k,v])=>`<div><b>${escapeHtml(k)}:</b> ${escapeHtml(String(v))}</div>`).join('')}</div>`).join(''):'<p>Numune kaydı yok.</p>';}
async function renderActions(){const el=document.getElementById('actionsList');try{const r=await fetch('/api/actions',{headers:API_HEADERS()});const j=await r.json();if(!r.ok)throw new Error(j.error);el.innerHTML=(j.actions||[]).length?(j.actions||[]).map(a=>`<div class="action-card"><div><b>${escapeHtml(a.description||a.title)}</b><div>${escapeHtml(a.dueDate||'Tarih yok')} · ${escapeHtml(a.priority||'normal')}</div></div><button onclick="toggleAction('${a.id}','${a.status==='done'?'open':'done'}')">${a.status==='done'?'Aç':'Tamamla'}</button></div>`).join(''):'<p>Aksiyon yok.</p>'; }catch(e){el.innerHTML='<p>'+escapeHtml(e.message)+'</p>';}}
async function submitAction(e){e.preventDefault();const fd=new FormData(e.target),companyId=document.getElementById('actionCompany')?.value||fd.get('companyId')||'',description=document.getElementById('actionTitle')?.value||fd.get('title')||fd.get('description')||'',dueDate=document.getElementById('actionDueDate')?.value||fd.get('dueDate')||'';const r=await fetch('/api/actions',{method:'POST',headers:API_HEADERS(),body:JSON.stringify({companyId,description,dueDate,actionType:'follow_up'})});const j=await r.json();if(!r.ok){alert(j.error||'Eklenemedi');return;}e.target.reset();renderActions();}
async function toggleAction(id,status){await fetch('/api/actions/'+encodeURIComponent(id),{method:'PUT',headers:API_HEADERS(),body:JSON.stringify({status})});renderActions();}
async function renderNotifications(){const el=document.getElementById('notificationsList');try{const r=await fetch('/api/notifications',{headers:API_HEADERS()});const j=await r.json();el.innerHTML=(j.notifications||[]).length?(j.notifications||[]).map(n=>`<div class="notification-card ${n.read||n.readAt?'':'unread'}" onclick="readNotification('${n.id}')"><b>${escapeHtml(n.title||'Bildirim')}</b><div>${escapeHtml(n.message||'')}</div><small>${escapeHtml(formatDate(new Date(n.createdAt)))}</small></div>`).join(''):'<p>Bildirim yok.</p>';}catch(e){el.innerHTML='<p>'+escapeHtml(e.message)+'</p>';}}
async function readNotification(id){await fetch('/api/notifications/'+encodeURIComponent(id)+'/read',{method:'PUT',headers:API_HEADERS()});renderNotifications();}
function showCompanyDetail(id){const c=myCompanies().find(x=>String(x.id)===String(id));if(!c)return;const visits=allVisitsForCompany(c.id),h=health(c),samples=samplesFor(c);document.getElementById('companyDetailTitle').textContent=c.name;document.getElementById('companyDetailBody').innerHTML=`<div class="detail-grid"><div><b>Bölge</b><span>${escapeHtml(c.bolge||'-')}</span></div><div><b>Ziyaret Periyodu</b><span>${escapeHtml((c.weeks||[]).join(', ')||'-')}</span></div><div><b>Atanmış Teknik Servis</b><span>${escapeHtml((SD.technicians||[]).find(t=>String(t.id)===String(c.techId))?.name||c.techId||'-')}</span></div><div><b>Son Giden</b><span>${escapeHtml(visits[0]?techLabel(visits[0]):'-')}</span></div><div><b>Sağlık Skoru</b><span>${h.score} · ${h.label}</span></div><div><b>Açık Numune</b><span>${samples.filter(sampleOpen).length}</span></div></div><h3>Skor Nedenleri</h3><p>${h.reasons.length?h.reasons.map(escapeHtml).join(' · '):'Olumsuz kayıt yok'}</p><h3>Ziyaretler</h3>${visits.length?visits.map(v=>`<div class="visit-entry"><b>${formatDate(v._date)} · ${v._type==='extra'?'Program Dışı':'Normal'}</b><div>${escapeHtml(techLabel(v))}</div>${visitDetails(v)}</div>`).join(''):'<p>Kayıt yok</p>'}<h3>Numuneler</h3>${samples.length?samples.map(s=>`<div class="sample-card">${Object.entries(s).filter(([k,v])=>v!==''&&v!=null&&typeof v!=='object').map(([k,v])=>`<div><b>${escapeHtml(k)}:</b> ${escapeHtml(String(v))}</div>`).join('')}</div>`).join(''):'<p>Kayıt yok</p>'}`;document.getElementById('companyDetailModal').classList.remove('hidden');}
function closeCompanyDetail(){document.getElementById('companyDetailModal')?.classList.add('hidden');}
function populateActionCompanies(){const s=document.getElementById('actionCompany');if(s)s.innerHTML='<option value="">Firma seçin</option>'+myCompanies().map(c=>`<option value="${escapeHtml(c.id)}">${escapeHtml(c.name)}</option>`).join('');}
function showPageHook(){if(currentPage==='aksiyonlar')populateActionCompanies();}
const _showPage=showPage;showPage=function(name){_showPage(name);if(name==='aksiyonlar')populateActionCompanies();};
function formatDate(d){if(!d||isNaN(d))return'-';return new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d);}
function escapeHtml(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function toggleMobileMenu(){document.body.classList.toggle('mobile-menu-open');}
function closeMobileMenu(){document.body.classList.remove('mobile-menu-open');}
function toggleUserMenu(){document.getElementById('userDropdown')?.classList.toggle('hidden');}
function doLogout(){localStorage.removeItem('token');sessionStorage.removeItem('token');localStorage.removeItem('sd_user');sessionStorage.removeItem('sd_user');location.href='index.html';}
window.showPage=showPage;window.showCompanyDetail=showCompanyDetail;window.closeCompanyDetail=closeCompanyDetail;window.toggleAction=toggleAction;window.readNotification=readNotification;window.toggleUserMenu=toggleUserMenu;window.doLogout=doLogout;
