const express=require('express');
const auth=require('../middleware/auth');
const {readState,mutateState}=require('../utils/stateStore');
const router=express.Router();
const isAdmin=u=>String(u?.role||'').toLowerCase()==='admin';
const isSales=u=>String(u?.role||'').toLowerCase()==='sales';
function repFor(state,user){const reps=Array.isArray(state.sd_st)?state.sd_st:[];const rep=reps.find(r=>String(r.userId||'')===String(user.id))||reps.find(r=>String(r.username||'').toLowerCase()===String(user.username||'').toLowerCase())||null;if(!rep)return null;const app=(state.sd_users||[]).find(u=>String(u.username||'').toLowerCase()===String(user.username||'').toLowerCase());return {...rep,userId:rep.userId||user.id,legacyUserId:rep.legacyUserId||app?.id||''};}
function visible(state,user){const all=Array.isArray(state.sd_notifications)?state.sd_notifications:[];if(isAdmin(user))return all;const rep=repFor(state,user);return rep?all.filter(n=>String(n.recipientUserId||n.salesRepId||'')===String(rep.id)):[];}
router.use(auth);router.use((req,res,next)=>(isAdmin(req.user)||isSales(req.user))?next():res.status(403).json({error:'Bu modüle erişim yetkiniz yok'}));
router.get('/',async(req,res)=>{try{const {state}=await readState();const rows=visible(state,req.user).sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))).slice(0,100);res.json({success:true,notifications:rows,count:rows.length});}catch(e){res.status(500).json({error:'Bildirimler okunamadı',details:e.message});}});
router.get('/unread/count',async(req,res)=>{try{const {state}=await readState();res.json({success:true,unread_count:visible(state,req.user).filter(n=>!(n.read||n.readAt)).length});}catch(e){res.status(500).json({error:'Sayı okunamadı'});}});
router.put('/all/read',async(req,res)=>{try{let updated=0;await mutateState(state=>{const ids=new Set(visible(state,req.user).map(n=>String(n.id)));state.sd_notifications=(state.sd_notifications||[]).map(n=>ids.has(String(n.id))&&!(n.read||n.readAt)?(updated++,{...n,read:true,readAt:new Date().toISOString()}):n);},req.user.id);res.json({success:true,updated});}catch(e){res.status(500).json({error:'Güncellenemedi'});}});
router.put('/:id/read',async(req,res)=>{try{await mutateState(state=>{const ids=new Set(visible(state,req.user).map(n=>String(n.id)));if(!ids.has(String(req.params.id)))throw Object.assign(new Error('Bildirim bulunamadı'),{statusCode:404});state.sd_notifications=(state.sd_notifications||[]).map(n=>String(n.id)===String(req.params.id)?{...n,read:true,readAt:new Date().toISOString()}:n);},req.user.id);res.json({success:true});}catch(e){res.status(e.statusCode||500).json({error:e.message});}});
router.delete('/:id',async(req,res)=>{try{await mutateState(state=>{const ids=new Set(visible(state,req.user).map(n=>String(n.id)));if(!ids.has(String(req.params.id)))throw Object.assign(new Error('Bildirim bulunamadı'),{statusCode:404});state.sd_notifications=(state.sd_notifications||[]).filter(n=>String(n.id)!==String(req.params.id));},req.user.id);res.json({success:true});}catch(e){res.status(e.statusCode||500).json({error:e.message});}});
module.exports=router;
