const express = require('express');
const db = require('../config/database');
const auth = require('../middleware/auth');
const router = express.Router();
async function readState(){await db.ready();if(db.dialect==='postgres'){const r=await db.raw.query("SELECT payload,updated_at FROM app_state WHERE state_key='main'");return {state:r.rows[0]?.payload||{},updatedAt:r.rows[0]?.updated_at||null};}return await new Promise((resolve,reject)=>db.get("SELECT payload,updated_at FROM app_state WHERE state_key='main'",[],(e,row)=>e?reject(e):resolve({state:row?JSON.parse(row.payload||'{}'):{},updatedAt:row?.updated_at||null})));}
router.get('/',auth,async(req,res)=>{res.set('Cache-Control','no-store, no-cache, must-revalidate, private');res.set('Pragma','no-cache');res.set('Expires','0');try{const r=await readState();res.json({success:true,...r});}catch(err){res.status(500).json({error:'State read failed',details:err.message});}});
router.put('/',auth,async(req,res)=>{try{await db.ready();let state=req.body?.state;if(!state||typeof state!=='object')return res.status(400).json({error:'Geçerli state gerekli'});const isOwner=String(req.user.username||'').toLowerCase()==='barkin.kayaci';if(!isOwner){const current=(await readState()).state||{};['sd_cfg','sd_users','sd_te','sd_vi','sd_ex','sd_dp'].forEach(k=>{if(Object.prototype.hasOwnProperty.call(current,k))state[k]=current[k];else delete state[k];});}
if(db.dialect==='postgres')await db.raw.query(`INSERT INTO app_state(state_key,payload,updated_by,updated_at) VALUES('main',$1::jsonb,$2,NOW()) ON CONFLICT(state_key) DO UPDATE SET payload=EXCLUDED.payload,updated_by=EXCLUDED.updated_by,updated_at=NOW()`,[JSON.stringify(state),req.user.id]);else await new Promise((resolve,reject)=>db.run("INSERT OR REPLACE INTO app_state(state_key,payload,updated_by,updated_at) VALUES('main',?,?,CURRENT_TIMESTAMP)",[JSON.stringify(state),req.user.id],e=>e?reject(e):resolve()));res.json({success:true,updatedAt:new Date().toISOString(),ownerWrite:isOwner});}catch(err){res.status(500).json({error:'State save failed',details:err.message});}});
module.exports=router;
